[package]
name = "question_1"
version = "0.1.0"
authors = ["Jamil4321 <jamil.ahmed.ja28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
